name: Docker Build

on:
  release:
    types: [published]

jobs:
  build:
    name: "Build and deploy"

    runs-on: "ubuntu-latest"

    strategy:
      matrix:
        actions-with-docker-image:
          - "magento-php-apache"
          - "magento-varnish"
          - "magento-elasticsearch"

    env:
      DOCKER_USERNAME: "bavaan"
      ACTIONS_ALLOW_UNSECURE_COMMANDS: true

    steps:
      - name: "Checkout"
        uses: "actions/checkout@v2"

      - name: "Grab version number"
        uses: "olegtarasov/get-tag@v1"
        id: "tagName"

      - name: "Build Docker image"
        run: "docker build --tag bavaan/${{ matrix.actions-with-docker-image }}:latest ${{ matrix.actions-with-docker-image }}/."

      - name: "Docker Login"
        run: "echo ${{ secrets.DOCKER_PASSWORD }} | $(which docker) login --password-stdin --username ${{ env.DOCKER_USERNAME }}"

      - name: "Push Docker image (latest)"
        run: "docker push bavaan/${{ matrix.actions-with-docker-image }}:latest"

      - name: "Tag Docker image (versioned)"
        run: "docker tag bavaan/${{ matrix.actions-with-docker-image }} bavaan/${{ matrix.actions-with-docker-image }}:${{ steps.tagName.outputs.tag }}"

      - name: "Push Docker image (versioned)"
        run: "docker push bavaan/${{ matrix.actions-with-docker-image }}:${{ steps.tagName.outputs.tag }}"

      - name: "Docker Logout"
        run: "docker logout"