name: Build Magento Php Apache Images

on:
  push:
    paths:
      - 'build/apache/**'

jobs:
  build:
    name: "Build and deploy magento apache"

    runs-on: "ubuntu-latest"

    strategy:
      matrix:
        php-version:
          # - "7.1"
          # - "7.2"
          - "7.3"
          - "7.4"
        actions-with-docker-image:
          - "magento-php-apache"
    env:
      DOCKER_USERNAME: "bavaan"

    steps:
      - name: "Checkout"
        uses: "actions/checkout@v2"

      - name: "Grab version number"
        uses: "olegtarasov/get-tag@v1"
        id: "tagName"

      - name: "Build Docker image"
        run: "docker build --tag bavaan/${{ matrix.actions-with-docker-image }}:${{ matrix.php-version }} build/apache/. -f build/apache/php-${{ matrix.php-version }}/Dockerfile"

      - name: "Docker Login"
        run: "echo ${{ secrets.DOCKER_PASSWORD }} | $(which docker) login --password-stdin --username ${{ env.DOCKER_USERNAME }}"

      - name: "Push Docker image (latest)"
        run: "docker push bavaan/${{ matrix.actions-with-docker-image }}:${{ matrix.php-version }}"

      - name: "Docker Logout"
        run: "docker logout"